/*
Copyright 2019 @foostan
Copyright 2020 Drashna Jaelre <@drashna>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include QMK_KEYBOARD_H

// // Tap Dance Declarations
// enum {
//   TD_ESC_CAPS = 0
// };

// // Tap Dance Definitions
// tap_dance_action_t tap_dance_actions[] = {
//   // Tap once for Esc, twice for Caps Lock
//   [TD_ESC_CAPS] = ACTION_TAP_DANCE_DOUBLE(KC_ESC, KC_CAPS),
// };

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ,-----------------------------------------.                ,-----------------------------------------.
 * | TAB  |  Q   |  W   |  E   |  R   |  T   |                |  Y   |  U   |  I   |  O   |  P   | DEL  |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | LALT |  A   |  S   |  D   |  F   |  G   |                |  H   |  J   |  K   |  L   | SCLN | QUOT |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | LSFT |  Z   |  X   |  C   |  V   |  B   |                |  N   |  M   | COMM | DOT  | SLSH | ENT  |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 *                             | LCTL |MO(1) | SPC  |  | BSPC |MO(2) | LGUI |
 *                             `--------------------'  `--------------------'
 *                                                                               generated by [keymapviz] */
        [0] = LAYOUT_split_3x6_3(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_DEL, KC_LALT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ENT, KC_LCTL, MO(1), KC_SPC, KC_BSPC, MO(2), KC_LGUI),

/* ,-----------------------------------------.                ,-----------------------------------------.
 * | GRV  |  1   |  2   |  3   |  4   |  5   |                |  6   |  7   |  8   |  9   |  0   | MINS |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      |      | PIPE | DQUO | LBRC |                | RBRC | QUOT | BSLS |      |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      |      | UNDS | LPRN | MINS |                | EQL  | RPRN | PLUS |      |      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 *                             |      |      | LSFT |  | RSFT |      |      |
 *                             `--------------------'  `--------------------'
 *                                                                               generated by [keymapviz] */
        [1] = LAYOUT_split_3x6_3(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_NO, KC_NO, KC_NO, KC_PIPE, KC_DQUO, KC_LBRC, KC_RBRC, KC_QUOT, KC_BSLS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_UNDS, KC_LPRN, KC_MINS, KC_EQL, KC_RPRN, KC_PLUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_LSFT, KC_RSFT, KC_TRNS, KC_NO),

/* ,-----------------------------------------.                ,-----------------------------------------.
 * | CAPS |  F1  |  F2  |  F3  |  F4  |  F5  |                |      |      |  UP  |      |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * | ESC  |      |  F6  |  F7  |  F8  |  F9  |                |      | LEFT | DOWN | RGHT |      |      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      | F10  | F11  | F12  | F14  | F15  |                |      |      |      |      |      |      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 *                             |      |      |TO(3) |  |      |      |      |
 *                             `--------------------'  `--------------------'
 *                                                                               generated by [keymapviz] */
        [2] = LAYOUT_split_3x6_3(KC_CAPS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_NO, KC_NO, KC_UP, KC_NO, KC_NO, KC_NO, KC_ESC, KC_NO, KC_F6, KC_F7, KC_F8, KC_F9, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_NO, KC_F10, KC_F11, KC_F12, KC_F14, KC_F15, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, TO(3), KC_NO, KC_TRNS, KC_NO),

/* ,-----------------------------------------.                ,-----------------------------------------.
 * |      |      |      |      |      |      |                |      |      |RGB_TO|RGB_MO|RGB_RM|      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |      |      |      |      |      |      |                |TO(0) |      |RGB_VA|RGB_HU|RGB_SA|      |
 * |------+------+------+------+------+------|                |------+------+------+------+------+------|
 * |QK_BOO|      |      |      |      |      |                |      |      |RGB_VA|RGB_HU|RGB_SA|      |
 * `------+------+------+------+------+------+------.  ,------+------+------+------+------+------+------|
 *                             | MPRV | MUTE | VOLD |  | VOLU | MPLY | MNXT |
 *                             `--------------------'  `--------------------'
 *                                                                               generated by [keymapviz] */
        [3] = LAYOUT_split_3x6_3(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, RGB_MOD, RGB_RMOD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_NO, RGB_VAI, RGB_HUI, RGB_SAI, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_VAD, RGB_HUD, RGB_SAD, KC_NO, KC_MPRV, KC_MUTE, KC_VOLD, KC_VOLU, KC_MPLY, KC_MNXT)
};
